spring.application.name=first_mcp_server
spring.ai.mcp.server.name=FirstMCPServer
spring.ai.mcp.server.version=0.0.1

spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync
# spring.ai.mcp.server.port=8090
